services:
  web:
    build: .
    image: test-container
    working_dir: /app
    restart: on-failure
    platform: linux/x86_64
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

